apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-admin
  namespace: kong
spec:
  port:
    targetPort: kong-admin
  to:
    kind: Service
    name: kong-kong-admin
    weight: null
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-manager
  namespace: kong
spec:
  port:
    targetPort: kong-manager
  to:
    kind: Service
    name: kong-kong-manager
    weight: null
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-manager-tls
  namespace: kong
spec:
  port:
    targetPort: kong-manager-tls
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kong-kong-manager
    weight: null
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-admin-tls
  namespace: kong
spec:
  port:
    targetPort: kong-admin-tls
  tls:
    termination: passthrough
  to:
    kind: Service
    name: kong-kong-admin
    weight: null