# This job patches KONG_CLUSTER_CONTROL_PLANE KONG_CLUSTER_TELEMETRY_ENDPOINT
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kong-dp
  name: patch-job
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: kong-dp
  name: patch-deploy
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: patch-job 
      volumes:
      - name: patch-job
        configMap:
          name: patch-deploy
          defaultMode: 0711 
      containers:
      - image: cmwylie19/kube-argo-base
        name: patch-deploy
        resources: {}
        volumeMounts:
        - name: patch-job
          mountPath: /opt/scripts
        securityContext:
           runAsUser: 0
        command: ["sh","-c","/opt/scripts/patch-job.sh"]
---
apiVersion: v1
data:
  patch-job.sh: |
    #!/bin/bash
    set -eu

    sleep 30
    # Get Server
    SERVER=$(oc get routes -n openshift-gitops redhat-kong-gitops-server -otemplate='{{ .spec.host }}')

    echo $SERVER

    # Get Password
    PASSWORD=$(oc get secret -n openshift-gitops redhat-kong-gitops-cluster -ojsonpath='{.data.admin\.password}' | base64 -d)
    echo $PASSWORD


    # Login Argo
    argocd login --username admin --password $PASSWORD $SERVER --insecure

    # Patch KONG_CLUSTER_CONTROL_PLANE
    argocd app patch-resource dp-kong --kind Deployment --resource-name dp-kong-kong --namespace=kong --patch "{\"spec\": { \"template\" : { \"spec\" : {\"containers\":[{\"name\":\"proxy\",\"env\": [{ \"name\" : \"KONG_CLUSTER_CONTROL_PLANE\", \"value\": \"$(oc get cm -n kong cluster-urls --template='{{.data.CLUSTER_URL}}'):8005\" }]}]}}}}"  --patch-type 'application/strategic-merge-patch+json'
    
    # Patch KONG_CLUSTER_TELEMETRY_ENDPOINT
    argocd app patch-resource dp-kong --kind Deployment --resource-name dp-kong-kong --namespace=kong --patch "{\"spec\": { \"template\" : { \"spec\" : {\"containers\":[{\"name\":\"proxy\",\"env\": [{ \"name\" : \"KONG_CLUSTER_TELEMETRY_ENDPOINT\", \"value\": \"$(oc get cm -n kong cluster-urls --template='{{.data.CLUSTER_TELEMETRY_URL}}'):8006\" }]}]}}}}"  --patch-type 'application/strategic-merge-patch+json'
kind: ConfigMap
metadata:
  namespace: kong-dp
  name: patch-deploy
---
# sa needs to get secrets, routes, in kong and openshift-gitops namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-job
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - anyuid
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-job-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-job
subjects:
- kind: ServiceAccount
  name: patch-job
  namespace: kong