apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: dp-kong-kong-proxy
  namespace: kong
spec:
  port:
    targetPort: kong-proxy
  to:
    kind: Service
    name: dp-kong-kong-proxy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kong-kong-proxy-tls
  namespace: kong
spec:
  port:
    targetPort: kong-proxy-tls
  tls:
    termination: passthrough
  to:
    kind: Service
    name: dp-kong-kong-proxy
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grafana-service
  namespace: kong
spec:
  port:
    targetPort: grafana
  to:
    kind: Service
    name: grafana-service
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    operated-prometheus: "true"
  name: prometheus-service
  namespace: kong
spec:
  port:
    targetPort: web
  to:
    kind: Service
    name: prometheus-operated