---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-license-secret
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: dataplane
  source:
    repoURL: 'https://github.com/mpaulgreen/kong-cp.git'
    path: gateway/prereqs/infra/vault
    targetRevision: cw-structure
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://api.mso-test-cwylie.fsi-env2.rhecoeng.com:6443
    namespace: kong
  syncPolicy:
    automated: # automatically sync repo changes
      prune: true
      selfHeal: true