apiVersion: v1
kind: Service
metadata:
  name: {{ include "productpage.name" . }}
  labels:
    app: productpage
    service: productpage
spec:
  ports:
    - port: 9080
      name: http
  selector:
    app: productpage
