# All roles needs to bve reviewed and narrowed down

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-kong
rules:
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  verbs:
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - secrets
  - services
  verbs:
  - create
  - patch
# must patch routes for postinstall
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - patch
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-kong-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-kong
subjects:
- kind: ServiceAccount
  name: redhat-kong-gitops-argocd-application-controller
  namespace: openshift-gitops

# Added following to overcome the permission issues. Need to revisit it in future.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-kong-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-secrets
  namespace: kong
rules:
  # needed to read the cluster.crt and cluster.key
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use
  # needed to create the secret
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-to-secrets
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-secrets
  namespace: kong-dp
rules:
  # needed to read the cluster.crt and cluster.key
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use
  # needed to create the secret
  - verbs:
      - create
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-to-secrets
  namespace: kong-dp
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong-dp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets
# Applying Casey's roles
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-perms
  namespace: kong
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - services
    verbs:
    - patch
  - apiGroups:
    - apps
    resources:
    - statefulsets
    verbs:
    - patch
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ayuid-to-postgres
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: postgres-perms