apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gitops-kong
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - create
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - patch
  - create
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-kong-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gitops-kong
subjects:
- kind: ServiceAccount
  name: redhat-kong-gitops-argocd-application-controller
  namespace: openshift-gitops

# Added following to overcome the permission issues. Need to revisit it in future.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-kong-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: redhat-kong-gitops-argocd-application-controller
  namespace: openshift-gitops
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: access-secrets
  namespace: kong
rules:
  - verbs:
      - get
      - list
      - watch
      - update
      - create
      - delete
    apiGroups:
      - ''
    resources:
      - secrets
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-to-secrets
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets

# The following have ot be tested
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scc-anyuid
  namespace: kong
rules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kong-to-scc-anyuid
  namespace: kong
subjects:
  - kind: ServiceAccount
    name: kong
    namespace: kong
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scc-anyuid
