apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: kong-session-config
  namespace: kong
data:
  admin_gui_session_conf: eyJjb29raWVfbmFtZSI6ImFkbWluX3Nlc3Npb24iLCJjb29raWVfc2FtZXNpdGUiOiJvZmYiLCJzZWNyZXQiOiJrb25nIiwiY29va2llX3NlY3VyZSI6ZmFsc2UsInN0b3JhZ2UiOiJrb25nIn0K
  portal_session_conf: eyJjb29raWVfbmFtZSI6InBvcnRhbF9zZXNzaW9uIiwiY29va2llX3NhbWVzaXRlIjoib2ZmIiwic2VjcmV0Ijoia29uZyIsImNvb2tpZV9zZWN1cmUiOmZhbHNlLCJzdG9yYWdlIjoia29uZyJ9Cg==
