apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  labels:
    app: kong-demo
  name: kong-keycloak
  namespace: keycloak
spec:
  externalAccess:
    enabled: true
  instances: 1
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: kong-realm
  namespace: keycloak
  labels:
    app: kong-demo
spec:
  instanceSelector:
    matchLabels:
      app: kong-demo
  realm:
    displayName: Kong Realm
    enabled: true
    id: kong
    realm: kong
    roles:
      realm:
        - name: customer
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: kermit-user
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: kong-demo
  user:
    credentials:
      - type: password
        value: kong
    email: kthefrog@example.com
    enabled: true
    firstName: Kermit
    lastName: The Frog
    username: kermit
    realmRoles:
      - customer
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakUser
metadata:
  name: bob-user
  namespace: keycloak
spec:
  realmSelector:
    matchLabels:
      app: kong-demo
  user:
    credentials:
      - type: password
        value: kong
    email: bob@example.com
    enabled: true
    firstName: Bob
    username: bob