apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postinstall
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kong
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: gateway/postinstall/cp
    repoURL: https://github.com/mpaulgreen/kong-cp.git
    targetRevision: main # branch
  syncPolicy:
    automated: # automatically sync repo changes
      prune: true
      selfHeal: true